<?php
/**
 * AcceptedPayment
 *
 * PHP version 5
 *
 * @category Class
 * @package  CrmCareCloud\Webservice\RestApi\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * REST API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@carecloud.cz
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.26
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace CrmCareCloud\Webservice\RestApi\Client\Model;

use \ArrayAccess;
use \CrmCareCloud\Webservice\RestApi\Client\ObjectSerializer;

/**
 * AcceptedPayment Class Doc Comment
 *
 * @category Class
 * @description The structure contains values for applied rewards, vouchers, discounts, and other benefits.
 * @package  CrmCareCloud\Webservice\RestApi\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AcceptedPayment implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'AcceptedPayment';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string,string>
      */
    protected static $swaggerTypes = [
        'recommended_discounts' => '\CrmCareCloud\Webservice\RestApi\Client\Model\DiscountItem[]',
'credit_points' => 'float',
'price_of_credit_points' => 'float',
'credit' => 'float',
'vouchers' => '\CrmCareCloud\Webservice\RestApi\Client\Model\PaymentVoucher[]',
'credit_points_of_this_transaction' => 'float',
'total_credit_points' => 'float',
'total_credit' => 'float',
'messages' => '\CrmCareCloud\Webservice\RestApi\Client\Model\CashierMessage[]'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string,string|null>
      */
    protected static $swaggerFormats = [
        'recommended_discounts' => null,
'credit_points' => 'float',
'price_of_credit_points' => 'float',
'credit' => 'float',
'vouchers' => null,
'credit_points_of_this_transaction' => 'float',
'total_credit_points' => 'float',
'total_credit' => 'float',
'messages' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string,string>
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string,string|null>
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'recommended_discounts' => 'recommended_discounts',
'credit_points' => 'credit_points',
'price_of_credit_points' => 'price_of_credit_points',
'credit' => 'credit',
'vouchers' => 'vouchers',
'credit_points_of_this_transaction' => 'credit_points_of_this_transaction',
'total_credit_points' => 'total_credit_points',
'total_credit' => 'total_credit',
'messages' => 'messages'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'recommended_discounts' => 'setRecommendedDiscounts',
'credit_points' => 'setCreditPoints',
'price_of_credit_points' => 'setPriceOfCreditPoints',
'credit' => 'setCredit',
'vouchers' => 'setVouchers',
'credit_points_of_this_transaction' => 'setCreditPointsOfThisTransaction',
'total_credit_points' => 'setTotalCreditPoints',
'total_credit' => 'setTotalCredit',
'messages' => 'setMessages'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'recommended_discounts' => 'getRecommendedDiscounts',
'credit_points' => 'getCreditPoints',
'price_of_credit_points' => 'getPriceOfCreditPoints',
'credit' => 'getCredit',
'vouchers' => 'getVouchers',
'credit_points_of_this_transaction' => 'getCreditPointsOfThisTransaction',
'total_credit_points' => 'getTotalCreditPoints',
'total_credit' => 'getTotalCredit',
'messages' => 'getMessages'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['recommended_discounts'] = isset($data['recommended_discounts']) ? $data['recommended_discounts'] : null;
        $this->container['credit_points'] = isset($data['credit_points']) ? $data['credit_points'] : null;
        $this->container['price_of_credit_points'] = isset($data['price_of_credit_points']) ? $data['price_of_credit_points'] : null;
        $this->container['credit'] = isset($data['credit']) ? $data['credit'] : null;
        $this->container['vouchers'] = isset($data['vouchers']) ? $data['vouchers'] : null;
        $this->container['credit_points_of_this_transaction'] = isset($data['credit_points_of_this_transaction']) ? $data['credit_points_of_this_transaction'] : null;
        $this->container['total_credit_points'] = isset($data['total_credit_points']) ? $data['total_credit_points'] : null;
        $this->container['total_credit'] = isset($data['total_credit']) ? $data['total_credit'] : null;
        $this->container['messages'] = isset($data['messages']) ? $data['messages'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets recommended_discounts
     *
     * @return \CrmCareCloud\Webservice\RestApi\Client\Model\DiscountItem[]
     */
    public function getRecommendedDiscounts()
    {
        return $this->container['recommended_discounts'];
    }

    /**
     * Sets recommended_discounts
     *
     * @param \CrmCareCloud\Webservice\RestApi\Client\Model\DiscountItem[] $recommended_discounts The list of offered discounts excludes rewards (Loyalty Status Discount).
     *
     * @return $this
     */
    public function setRecommendedDiscounts($recommended_discounts)
    {
        $this->container['recommended_discounts'] = $recommended_discounts;

        return $this;
    }

    /**
     * Gets credit_points
     *
     * @return float
     */
    public function getCreditPoints()
    {
        return $this->container['credit_points'];
    }

    /**
     * Sets credit_points
     *
     * @param float $credit_points Amount of used points.
     *
     * @return $this
     */
    public function setCreditPoints($credit_points)
    {
        $this->container['credit_points'] = $credit_points;

        return $this;
    }

    /**
     * Gets price_of_credit_points
     *
     * @return float
     */
    public function getPriceOfCreditPoints()
    {
        return $this->container['price_of_credit_points'];
    }

    /**
     * Sets price_of_credit_points
     *
     * @param float $price_of_credit_points Amount of money corresponding to the number of used points.
     *
     * @return $this
     */
    public function setPriceOfCreditPoints($price_of_credit_points)
    {
        $this->container['price_of_credit_points'] = $price_of_credit_points;

        return $this;
    }

    /**
     * Gets credit
     *
     * @return float
     */
    public function getCredit()
    {
        return $this->container['credit'];
    }

    /**
     * Sets credit
     *
     * @param float $credit Amount of used credits.
     *
     * @return $this
     */
    public function setCredit($credit)
    {
        $this->container['credit'] = $credit;

        return $this;
    }

    /**
     * Gets vouchers
     *
     * @return \CrmCareCloud\Webservice\RestApi\Client\Model\PaymentVoucher[]
     */
    public function getVouchers()
    {
        return $this->container['vouchers'];
    }

    /**
     * Sets vouchers
     *
     * @param \CrmCareCloud\Webservice\RestApi\Client\Model\PaymentVoucher[] $vouchers List of applied rewards/vouchers on the current bill (includes the value of discount) independent of DiscountItem.
     *
     * @return $this
     */
    public function setVouchers($vouchers)
    {
        $this->container['vouchers'] = $vouchers;

        return $this;
    }

    /**
     * Gets credit_points_of_this_transaction
     *
     * @return float
     */
    public function getCreditPointsOfThisTransaction()
    {
        return $this->container['credit_points_of_this_transaction'];
    }

    /**
     * Sets credit_points_of_this_transaction
     *
     * @param float $credit_points_of_this_transaction Sum of points gained from this transaction.
     *
     * @return $this
     */
    public function setCreditPointsOfThisTransaction($credit_points_of_this_transaction)
    {
        $this->container['credit_points_of_this_transaction'] = $credit_points_of_this_transaction;

        return $this;
    }

    /**
     * Gets total_credit_points
     *
     * @return float
     */
    public function getTotalCreditPoints()
    {
        return $this->container['total_credit_points'];
    }

    /**
     * Sets total_credit_points
     *
     * @param float $total_credit_points Amount of the points on the customer account (after the recent purchase is closed).
     *
     * @return $this
     */
    public function setTotalCreditPoints($total_credit_points)
    {
        $this->container['total_credit_points'] = $total_credit_points;

        return $this;
    }

    /**
     * Gets total_credit
     *
     * @return float
     */
    public function getTotalCredit()
    {
        return $this->container['total_credit'];
    }

    /**
     * Sets total_credit
     *
     * @param float $total_credit Amount of the credits on the customer account (after the recent purchase is closed).
     *
     * @return $this
     */
    public function setTotalCredit($total_credit)
    {
        $this->container['total_credit'] = $total_credit;

        return $this;
    }

    /**
     * Gets messages
     *
     * @return \CrmCareCloud\Webservice\RestApi\Client\Model\CashierMessage[]
     */
    public function getMessages()
    {
        return $this->container['messages'];
    }

    /**
     * Sets messages
     *
     * @param \CrmCareCloud\Webservice\RestApi\Client\Model\CashierMessage[] $messages A recommendation messages for the cashier in his language localization.
     *
     * @return $this
     */
    public function setMessages($messages)
    {
        $this->container['messages'] = $messages;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
