<?php
/**
 * PointHistoryRecord
 *
 * PHP version 5
 *
 * @category Class
 * @package  CrmCareCloud\Webservice\RestApi\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * REST API Reference
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@carecloud.cz
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace CrmCareCloud\Webservice\RestApi\Client\Model;

use \ArrayAccess;
use \CrmCareCloud\Webservice\RestApi\Client\ObjectSerializer;

/**
 * PointHistoryRecord Class Doc Comment
 *
 * @category Class
 * @description Point history record.
 * @package  CrmCareCloud\Webservice\RestApi\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PointHistoryRecord implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'PointHistoryRecord';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string,string>
      */
    protected static $swaggerTypes = [
        'customer_id' => 'string',
        'amount' => 'float',
        'point_operation_type' => 'string',
        'point_operation_note' => 'string',
        'point_type_id' => 'string',
        'partner_id' => 'string',
        'store_id' => 'string',
        'point_history_record_time' => 'string',
        'extended_data' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string,string|null>
      */
    protected static $swaggerFormats = [
        'customer_id' => null,
        'amount' => 'float',
        'point_operation_type' => null,
        'point_operation_note' => null,
        'point_type_id' => null,
        'partner_id' => null,
        'store_id' => null,
        'point_history_record_time' => null,
        'extended_data' => 'json'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string,string>
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string,string|null>
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'customer_id' => 'customer_id',
        'amount' => 'amount',
        'point_operation_type' => 'point_operation_type',
        'point_operation_note' => 'point_operation_note',
        'point_type_id' => 'point_type_id',
        'partner_id' => 'partner_id',
        'store_id' => 'store_id',
        'point_history_record_time' => 'point_history_record_time',
        'extended_data' => 'extended_data'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'customer_id' => 'setCustomerId',
        'amount' => 'setAmount',
        'point_operation_type' => 'setPointOperationType',
        'point_operation_note' => 'setPointOperationNote',
        'point_type_id' => 'setPointTypeId',
        'partner_id' => 'setPartnerId',
        'store_id' => 'setStoreId',
        'point_history_record_time' => 'setPointHistoryRecordTime',
        'extended_data' => 'setExtendedData'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'customer_id' => 'getCustomerId',
        'amount' => 'getAmount',
        'point_operation_type' => 'getPointOperationType',
        'point_operation_note' => 'getPointOperationNote',
        'point_type_id' => 'getPointTypeId',
        'partner_id' => 'getPartnerId',
        'store_id' => 'getStoreId',
        'point_history_record_time' => 'getPointHistoryRecordTime',
        'extended_data' => 'getExtendedData'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['customer_id'] = isset($data['customer_id']) ? $data['customer_id'] : null;
        $this->container['amount'] = isset($data['amount']) ? $data['amount'] : null;
        $this->container['point_operation_type'] = isset($data['point_operation_type']) ? $data['point_operation_type'] : null;
        $this->container['point_operation_note'] = isset($data['point_operation_note']) ? $data['point_operation_note'] : null;
        $this->container['point_type_id'] = isset($data['point_type_id']) ? $data['point_type_id'] : null;
        $this->container['partner_id'] = isset($data['partner_id']) ? $data['partner_id'] : null;
        $this->container['store_id'] = isset($data['store_id']) ? $data['store_id'] : null;
        $this->container['point_history_record_time'] = isset($data['point_history_record_time']) ? $data['point_history_record_time'] : null;
        $this->container['extended_data'] = isset($data['extended_data']) ? $data['extended_data'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets customer_id
     *
     * @return string
     */
    public function getCustomerId()
    {
        return $this->container['customer_id'];
    }

    /**
     * Sets customer_id
     *
     * @param string $customer_id The unique ID of the customer.
     *
     * @return $this
     */
    public function setCustomerId($customer_id)
    {
        $this->container['customer_id'] = $customer_id;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return float
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param float $amount The number of points used in the point operation record.
     *
     * @return $this
     */
    public function setAmount($amount)
    {
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets point_operation_type
     *
     * @return string
     */
    public function getPointOperationType()
    {
        return $this->container['point_operation_type'];
    }

    /**
     * Sets point_operation_type
     *
     * @param string $point_operation_type Type of the point operation record.
     *
     * @return $this
     */
    public function setPointOperationType($point_operation_type)
    {
        $this->container['point_operation_type'] = $point_operation_type;

        return $this;
    }

    /**
     * Gets point_operation_note
     *
     * @return string
     */
    public function getPointOperationNote()
    {
        return $this->container['point_operation_note'];
    }

    /**
     * Sets point_operation_note
     *
     * @param string $point_operation_note Note of the point operation record.
     *
     * @return $this
     */
    public function setPointOperationNote($point_operation_note)
    {
        $this->container['point_operation_note'] = $point_operation_note;

        return $this;
    }

    /**
     * Gets point_type_id
     *
     * @return string
     */
    public function getPointTypeId()
    {
        return $this->container['point_type_id'];
    }

    /**
     * Sets point_type_id
     *
     * @param string $point_type_id Type of the point record.
     *
     * @return $this
     */
    public function setPointTypeId($point_type_id)
    {
        $this->container['point_type_id'] = $point_type_id;

        return $this;
    }

    /**
     * Gets partner_id
     *
     * @return string
     */
    public function getPartnerId()
    {
        return $this->container['partner_id'];
    }

    /**
     * Sets partner_id
     *
     * @param string $partner_id The unique ID of the partner company.
     *
     * @return $this
     */
    public function setPartnerId($partner_id)
    {
        $this->container['partner_id'] = $partner_id;

        return $this;
    }

    /**
     * Gets store_id
     *
     * @return string
     */
    public function getStoreId()
    {
        return $this->container['store_id'];
    }

    /**
     * Sets store_id
     *
     * @param string $store_id The unique ID of the store in CareCloud.
     *
     * @return $this
     */
    public function setStoreId($store_id)
    {
        $this->container['store_id'] = $store_id;

        return $this;
    }

    /**
     * Gets point_history_record_time
     *
     * @return string
     */
    public function getPointHistoryRecordTime()
    {
        return $this->container['point_history_record_time'];
    }

    /**
     * Sets point_history_record_time
     *
     * @param string $point_history_record_time Date and time of the point record from the point history. *(YYYY-MM-DD HH:MM:SS)*
     *
     * @return $this
     */
    public function setPointHistoryRecordTime($point_history_record_time)
    {
        $this->container['point_history_record_time'] = $point_history_record_time;

        return $this;
    }

    /**
     * Gets extended_data
     *
     * @return string
     */
    public function getExtendedData()
    {
        return $this->container['extended_data'];
    }

    /**
     * Sets extended_data
     *
     * @param string $extended_data Extended data are related to the point history as details about the purchase, point expiration, and others. Several parameters depend on the type of point operation.
     *
     * @return $this
     */
    public function setExtendedData($extended_data)
    {
        $this->container['extended_data'] = $extended_data;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
